# Title of your website
title: "Semagrow"


# The slogan describes your website and is used on homepage in <title> and other important places

slogan: "Data Intensive Techniques to Boost the Real-Time Performance of Global Agricultural Data Infrastructures"


# The description is used on homepage and in the footer to quickly
# describe your website. Use a maximum of 150 characters for SEO-purposes.

description: "Semagrow federated querying and data integration system"


# Main author of the website
# See > authors.yml
author: semagrow

# This URL is the main address for absolute links. Don't include a slash at the end.
#

url: "http://semagrow.github.io"
#url: "http://localhost:4000"
baseurl: ""

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/Phlow/feeling-responsive/edit/gh-pages

gems: [jekyll-paginate]


# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)

urlimg: 'http://semagrow.github.io/assets/img/'


# Logo size is 600x80 pixels
logo: "logo.png"


# Paginates all X entries
paginate: 5


# Pagination path: Important for blog page in /news/ to work
paginate_path: "news/page:num"


# Theme works best with Kramdown (using the table of contents function)

markdown: kramdown
permalink: /:categories/:title/
highlight: pygments
excerpt_separator: "<!--more-->"
include: ['.htaccess']

# Anything that starts with _ is excluded from copying
# into the production _site
# Exclude also these files:
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md


# The language setting is used in /includes/header.html for html-settings
language: "en"


# default.html front-matter and comress.html
# Options: http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]


##
## Default Settings
##

defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values: left, right. By default there will be no sidebar
      comments: false
      author: phlow     # Default author for pages
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values: left, right. By default there will be no sidebar
      comments: false
      author: phlow     # Default author for posts



##
##  Open _data/navigation.yml to adjust the left and right topbar navigation
##


##
## Verify Website to Webmaster Tools
##

google_author:             "https://plus.google.com/u/0/106502345197969472018"
#google_site_verification:  "Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ"
#bing_webmastertools_id:    "0FB4C028ABCF07C908C54386ABD2D97F"
# alexa_verify_id:         ""


##
## Favicons, Chrome, Android & Apple Touch Buttons
## More information: https://mathiasbynens.be/notes/touch-icons
##

favicon-32x32:                          "favicon-32x32.png"
touch-icon-192x192:                     "semagrow-200x200.png"
apple-touch-icon-180x180-precomposed:   "apple-touch-icon-180x180-precomposed.png"
apple-touch-icon-152x152-precomposed:   "apple-touch-icon-152x152-precomposed.png"
apple-touch-icon-144x144-precomposed:   "apple-touch-icon-144x144-precomposed.png"
apple-touch-icon-120x120-precomposed:   "apple-touch-icon-120x120-precomposed.png"
apple-touch-icon-114x114-precomposed:   "apple-touch-icon-114x114-precomposed.png"
apple-touch-icon-76x76-precomposed:     "apple-touch-icon-76x76-precomposed.png"
apple-touch-icon-72x72-precomposed:     "apple-touch-icon-72x72-precomposed.png"
apple-touch-icon-precomposed:           "apple-touch-icon-precomposed.png"
msapplication_tileimage:                "msapplication_tileimage.png"  # Size 144x144
msapplication_tilecolor:                "#fabb00"


##
## Facebook-Optimization: http://j.mp/fb_optimize
##

og_image:                           "logo-512x.png"
og_locale:                          "en_EN"
og_type:                            "website"
og_title:                           "The Semagrow Federated Querying Endpoint"
og_description:                     "Feeling Responsive is built on the fabulous Foundation Framework and comes with lots of features to show your content right."
# og_url:                           ""
# og_site_name:                     ""


##
## Social media
##  Open _data/socialmedia.yml to adjust the left and right topbar navigation
##


##
## Disqus
## used in _includes/comments
##

disqus_shortname: feelingresponsive


##
## SASS
## More: http://sass-lang.com/
## More: http://jekyllrb.com/docs/assets/#sassscss
##

sass:
    sass_dir: _sass
    style: :compressed


## https://www.google.com/analytics/
## used in _includes/footer_scripts

#google_analytics_tracking_id: UA-60112281-1


## tawk.to
## https://www.tawk.to/knowledgebase/
##
##  tawk.to is a free live chat app that lets you monitor and chat
##  with visitors on your website or from a free customizable page
##
##  To load the script add tawkto: true in front matter of each page
##
## used in _includes/footer_scripts

# tawkto_embed_uri:
